name: Makefile CI

on:
  push:
  schedule:
    - cron: 0 0 1 * *

jobs:
  build_and_publish:

    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Configure
        run: |
          set -xe
          ./configure

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: make

      - name: Publish
        run: make publish

      - name: Build full
        run: make build_full

      - name: Publish full
        run: make publish_full
